spring.application.name=Federated Chess
federation.domain=chessfed.tilera.xyz
federation.baseUrl=https://chessfed.tilera.xyz

spring.security.oauth2.client.registration.openid.client-id=chessfed
# Credentials for test server
spring.security.oauth2.client.registration.openid.client-secret=EHtjDzG6XoI4odghaiYeQcjC
spring.security.oauth2.client.registration.openid.scope=openid,profile,email
spring.security.oauth2.client.registration.openid.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.openid.redirect-uri=https://chessfed.tilera.xyz/login/oauth2/code/openid
spring.security.oauth2.client.provider.openid.issuer-uri=https://chessfed.tilera.xyz/dex