spring.application.name=Federated Chess
federation.domain=chessfed.tilera.xyz
federation.baseUrl=https://chessfed.tilera.xyz

spring.security.oauth2.client.registration.dex.client-id=chessfed
# Credentials for test server
spring.security.oauth2.client.registration.dex.client-secret=EHtjDzG6XoI4odghaiYeQcjC
spring.security.oauth2.client.registration.dex.scope=openid,profile,email
spring.security.oauth2.client.registration.dex.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.dex.redirect-uri=https://chessfed.tilera.xyz/login/oauth2/code/dex
spring.security.oauth2.client.provider.dex.issuer-uri=https://chessfed.tilera.xyz/dex