spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          openid:
            client-id: ${OIDC_ID}
            client-secret: ${OIDC_SECRET}
            scope: "openid,profile,email"
            authorization-grant-type: authorization_code
            redirect-uri: https://${APP_DOMAIN}/login/oauth2/code/openid
        provider:
          openid:
            issuer-uri: ${OIDC_ISSUER}
federation:
  domain: ${APP_DOMAIN}
  baseUrl: https://${APP_DOMAIN}